# Generated by Django 2.1.5 on 2019-10-29 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191029_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 9, 35, 52, 546433), verbose_name='date published'),
        ),
    ]
