# Generated by Django 2.1.5 on 2019-10-29 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191029_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 10, 26, 11, 728330), verbose_name='date published'),
        ),
    ]
